# Generated by Django 5.1.4 on 2025-01-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('workspace_slug', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
