# Generated by Django 5.1.4 on 2025-01-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='verified',
        ),
        migrations.AddField(
            model_name='memory',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='memory',
            name='workspace_slug',
            field=models.CharField(max_length=255),
        ),
    ]
