# Generated by Django 5.1.4 on 2025-01-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='machine',
            field=models.CharField(max_length=255),
        ),
    ]
